apiVersion: v1
kind: Pod
metadata:
  name: pod-nodelpool1
spec:
  nodeName: aks-nodepool1-19389025-vmss000000 
  containers:
  - name: pod-nodelpool1
    image: nginx
    resources:
      limits:
        memory: "28Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
