apiVersion: v1
kind: Pod
metadata:
  name: pod-dev 
  namespace: desenvolvimento
  labels:
    name: pod-dev
spec:
  containers:
  - name: pod-dev
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
